### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kenwang7477** [tobeylin/TobeyTrend#5]
切國家時偶爾發現的:

06-24 14:24:53.943  14305-14305/com.trend.tobeylin.tobeytrend E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.trend.tobeylin.tobeytrend, PID: 14305
    java.lang.NullPointerException
            at com.trend.tobeylin.tobeytrend.ui.TypeEditText$TypeTimerTask$1.run(TypeEditText.java:98)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5335)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by tobeylin** [comment]
Fix #5 in 0a07777df32e12c63514334f544323f2f9a2d664
